version: '3.3'

services:
  rtmp:
    build: .
    ports:
      - "1935:1935"
    container_name: rtmp_server
# services:
#   nginx:
#     build:
#         context: .
#         dockerfile: Dockerfile
#     ports:
#       - "80:80"
#       - "8080:8080"
#       - "1935:1935"